[package]
name = "seriesdb"
version = "0.1.0"
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2018"

[dependencies]
rocksdb = {git = "https://github.com/xuchaoqian/rust-rocksdb.git", branch = "master"}
bytes = "0.4"
byteorder = "1.3"
serde = "1.0.101"
rmp-serde = "0.14.0"