[package]
name = "seriesdb"
version = "0.5.0"
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2018"

[dependencies]
rocksdb = "0.19.0"
bytes = "0.6.0"
byteorder = "1.3.4"
serde = "1.0.117"
rmp-serde = "0.14.4"